### ISSUE TITLE
Some dissidents claimed that Buddhist prayer was compulsory in all government-run schools...

### ISSUE THREAD

**Issue by BKP05** [colaresi/AnnotationProjectPULSAR#24]
```
Some dissidents claimed that Buddhist prayer was compulsory in all government-run schools, 
however, the government contended that Buddhist teaching was permitted only in monastic 
schools and that religious teaching was forbidden in other schools.
```
This is about handling a long sentence (with *however*, contrast) and some general rules. 

The sentence is from __Societal Abuses and Discrimination__ subsection. I see three sub-sentences in it.

`Some dissidents claimed that Buddhist prayer was compulsory in all government-run schools`

`the government contended that Buddhist teaching was permitted only in monastic schools`

`the government contended that... religious teaching was forbidden in other schools.`

They all talk about religious teaching (__Buddhist prayer, Buddhist teaching, religious teaching__).  And the judgments are different (__compulsory, permitted only, forbidden__) at different locations (__all government-run schools, monastic schools, other schools__) from different sources (__some dissidents, the government__).   What do you think that we handle a very long sentence with sub-sentences. Then, do we need to tag/or link that they are all in the sentence?

**Comment by colaresi** [comment]
I think we can identify when everything is one sentence just from the original texts or keeping track of a sentence id.
When people are reading things, we do not need to break anything.
We need to break long sentences because of the syntactic parsers.

Do you think we should have annotators suggest breaks? I am not sure.

**Comment by BKP05** [comment]
I have just found another example while you were commenting, 

```
Ethnic-Nepalese Bhutanese claimed they were subject to discrimination and prejudice in 
employment, while the government insisted they were proportionally represented in civil 
service and government jobs.
```
The sentence is connected by __while__.  Even after breaking the sentence into two, the meaning does not really change.  One claimed that they were discrimination, and the other contends that there was no discrimination/prejudice. 

I agree that the annotators do not need to break, as you pointed out, we can easily track where a given sentence is from (section-subseciton-paragraph address and sentence number).  

I meant, when we have a very long sentence (with multiple sub-sentences in it), annotators need to pay attention to that there could be multiple aspects and multiple judgments and others.
