### ISSUE TITLE
Adding co-reference resolution for aspects and judgments?

### ISSUE THREAD

**Issue by colaresi** [colaresi/AnnotationProjectPULSAR#26]
Should we add a link for co-reference resolution, from co-reference to reference?

There are sentences such as 
```
The constitution protected freedom of speech and the press, but
the government did not respect these rights.
```
There would be a co-reference link from `these rights` to freedom of speech and from `these rights` the `the press`.

**Comment by BKP05** [comment]
I agree. Because ```these rights```  have the judgment (```did not respect```), we do not want to miss that.

**Comment by colaresi** [comment]
Added CoReferenceLink to PULSAR.dtd in SHA: 957325b2adb983cb53f28670a3ad5975e301285e
https://github.com/colaresi/AnnotationProjectPULSAR/commit/957325b2adb983cb53f28670a3ad5975e301285e#diff-110bc7bccec9906d4c0ee9e8f1a8f57d
