### ISSUE TITLE
Batch3 Nolan Troubleshoot

### ISSUE THREAD

**Issue by nolanroosa** [colaresi/AnnotationProjectPULSAR#31]
[NDRbatch3notes.xlsx](https://github.com/colaresi/AnnotationProjectPULSAR/files/1816973/NDRbatch3notes.xlsx)

**Comment by BKP05** [comment]
What's this? What am I supposed to look at?

**Comment by nolanroosa** [comment]
Mike told me to upload my notes, as far as I know they don't require any action
